- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.pythonrc:
    ~/.rtorrent.rc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zsh:
    ~/.zshrc:

- create:
  - ~/.rtorrent/session
  - ~/.rtorrent/watch
  - ~/.rtorrent/downloads

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    shell/plugins/
    vim/pack/vendor/start/
    zsh/plugins/
